# Week 1 - Numpy exercises

In [2]:
import numpy as np

**1. Create a 3x3 array with values ranging from 2 to 10.**

In [3]:
np.arange(2, 11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

**2. Create a zero 1D vector of size 10 and update the sixth value to 11.**

In [5]:
x = np.zeros(10)
print(x)
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


**3. Create a 8x8 binary matrix (just 1's and 0's) and fill it with a checkerboard pattern.**

In [11]:
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**4. Create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.**

In [12]:
np.diagflat([4, 5, 6, 8])

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

**5. Find the sum of all the positive integers that are multiples of either 3 or 5, and are less than 100.**

In [17]:
x = np.arange(1, 100)
# find  multiple of 3 or 5
n= x[(x % 3 == 0) | (x % 5 == 0)]
print(n.sum())

2318


**6. Create a 5x6 2D array with 0's along the first row, 1's along the second, etc.**

In [21]:
x = np.ones((5, 6))
y = np.expand_dims(np.arange(5), axis=1)
x*y

array([[0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4.]])

**7. Calculate the difference between neighboring elements, element-wise of the array [1 3 5 7 0].**

In [22]:
x = np.array([1, 3, 5, 7, 0])
np.diff(x)

array([ 2,  2,  2, -7])

**8. Compute $e^x - 1$, element-wise of a the array [1. 2. 3. 4.].**

In [23]:
x = np.array([1., 2., 3., 4.])
np.exp(x) - 1

array([ 1.71828183,  6.3890561 , 19.08553692, 53.59815003])